management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8888
spring:
    application:
        name: configServerSanteVista
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/AzaiezAbdessalem/config-serverSanteVista.git
                    username: AzaiezAbdessalem
                    password: 3c47865728bc6bc791e4e0f043070572a9f1a377
                    clone-on-start: true
                    skipSslValidation: true
                    default-label: dev
